// Product boundary only. This list never grants authority; the server does that.
export const MICA_PLATFORM_CAPABILITIES = Object.freeze([
    'PLATFORM_MANAGE', 'GLOBAL_USER_MANAGE', 'PLAN_MANAGE', 'ACCESS_ANY_ORG',
    'SUPPORT_IMPERSONATE', 'HARD_DELETE_EXCEPTIONAL', 'ORGANIZATION_CREATE',
    'ORGANIZATION_UPDATE', 'ORGANIZATION_ARCHIVE', 'PLATFORM_MIGRATIONS_APPLY',
    'PLATFORM_TENANTS_PROVISION', 'PLATFORM_SYSTEM_MONITOR', 'GLOBAL_CATALOG_VIEW',
    'GLOBAL_CATALOG_MANAGE', 'CATALOG_ASSIGN_ANY_ORG', 'RATE_MANAGE_ANY_ORG',
    'REPORT_COMPARE_SCOPED_ORGS', 'REPORT_CONSOLIDATED_SCOPED_ORGS',
    'SAAS_ANALYTICS_VIEW', 'AUDIT_PLATFORM_VIEW'
]);
export const MICA_ORGANIZATION_CAPABILITIES = Object.freeze([
    'ORG_VIEW', 'ORG_SETTINGS_VIEW', 'ORG_SETTINGS_MANAGE', 'ORG_MEMBER_VIEW',
    'ORG_MEMBER_INVITE', 'ORG_MEMBER_MANAGE', 'ORG_MEMBER_PERMISSION_MANAGE',
    'IMPORT_VIEW', 'IMPORT_CREATE', 'IMPORT_RETRY', 'IMPORT_REVIEW', 'RECORD_VIEW',
    'RECORD_CLASSIFY', 'RECORD_SOFT_DELETE', 'RECORD_RESTORE', 'PERCEPTION_IMPORT',
    'BANK_IMPORT', 'PAYROLL_IMPORT', 'ISSUE_RESOLVE', 'CATALOG_ORG_VIEW',
    'CATALOG_ACTIVITY_MANAGE', 'CATALOG_CATEGORY_MANAGE', 'REPORT_VIEW', 'REPORT_EXPORT',
    'TICKET_CREATE', 'TICKET_VIEW_ORG', 'AUDIT_VIEW_ORG', 'FINANCIAL_ALLOCATION_EDIT',
    'SENSITIVEDATA_BANKING_READ', 'SENSITIVEDATA_SALARIES_READ',
    'DOCUMENTS_UPLOAD', 'DOCUMENTS_OCR_PROCESS', 'DOCUMENTS_OCR_VERIFY'
]);

export function isMicaCapability(code, scope) {
    return (scope === 'PLATFORM' ? MICA_PLATFORM_CAPABILITIES :
        scope === 'ORGANIZATION' ? MICA_ORGANIZATION_CAPABILITIES : []).includes(code);
}
